#!/usr/bin/env bash
# Setup runner on thinkcentre.local for Maqui Linux development

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $*"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*"
}

# Configuration
REPO_DIR="$HOME/Work/maquilinux"
MQL_LOCAL="$REPO_DIR/mql.local"
RUNNER_SERVICE="actions.runner.maquilinux"
RUNNER_DIR="$HOME/actions-runner"

# Step 1: Clone repository if not exists
if [[ ! -d "$REPO_DIR" ]]; then
    log_info "Cloning repository to $REPO_DIR"
    mkdir -p "$(dirname "$REPO_DIR")"
    git clone https://github.com/glats/maquilinux.git "$REPO_DIR"
else
    log_info "Repository already exists at $REPO_DIR"
    cd "$REPO_DIR"
    git pull origin main
fi

# Step 2: Configure mql.local
log_info "Creating mql.local configuration"
cat > "$MQL_LOCAL" << EOF
# User overrides for Maqui Linux development on thinkcentre.local
# Generated by setup-runner.sh

# The disk is auto-mounted at /run/media/glats/maquilinux
MQL_LFS=/run/media/glats/maquilinux

# Optional: Override other variables as needed
# MQL_DISK=/dev/sdd1
# MQL_RELEASEVER=26.4
# MQL_REPO_DEST=/srv/glats/nginx/repo/maquilinux/26.4
EOF

log_info "mql.local created:"
cat "$MQL_LOCAL"

# Step 3: Ensure runner is installed
if [[ ! -d "$RUNNER_DIR" ]]; then
    log_warn "GitHub Actions runner not found at $RUNNER_DIR"
    log_warn "Please install the runner following GitHub's instructions:"
    log_warn "https://github.com/glats/maquilinux/settings/actions/runners/new"
    log_warn "Choose 'self-hosted' and download/configure for Linux x64"
    log_warn "Once installed, run: ./config.sh --url https://github.com/glats/maquilinux --token <TOKEN>"
    log_warn "Then start with: ./run.sh"
    log_warn "Alternatively, run in tmux:"
    log_warn "  tmux new-session -d -s runner 'cd $RUNNER_DIR && ./run.sh'"
    exit 1
fi

# Step 4: Restart runner in tmux if not running
if ! tmux has-session -t runner 2>/dev/null; then
    log_info "Starting runner in tmux session 'runner'"
    tmux new-session -d -s runner "cd $RUNNER_DIR && ./run.sh"
    log_info "Runner started in tmux session 'runner'"
    log_info "Attach with: tmux attach -t runner"
else
    log_info "Runner already running in tmux session 'runner'"
    log_info "Restarting runner..."
    tmux send-keys -t runner C-c
    sleep 2
    tmux send-keys -t runner "cd $RUNNER_DIR && ./run.sh" Enter
    log_info "Runner restarted"
fi

# Step 5: Test connection to GitHub
log_info "Testing runner connection to GitHub..."
if cd "$RUNNER_DIR" && ./config.sh --check 2>/dev/null; then
    log_info "Runner configuration appears valid"
else
    log_warn "Runner configuration check failed"
    log_warn "Please verify the runner is properly configured and has network access"
fi

log_info "Setup complete!"
log_info "Repository: $REPO_DIR"
log_info "Configuration: $MQL_LOCAL"
log_info "Runner status: $(tmux has-session -t runner && echo 'running' || echo 'stopped')"
log_info "Backup directory: ~/maqui-backups/ (default)"
log_info "Use 'mql backup create' to create backups before risky changes."