Name:           ninja
Version:        1.13.2
Release:        1.m264%{?dist}
Summary:        Small and fast build system focused on speed

%define debug_package        %{nil}
%define __debug_install_post %{nil}
%define __os_install_post    %{nil}

License:        Apache-2.0
URL:            https://ninja-build.org
Source0:        https://github.com/ninja-build/ninja/archive/refs/tags/v%{version}/ninja-%{version}.tar.gz

BuildRequires:  python3

%description
Ninja is a tiny build system with a focus on speed. It is designed to have its
input files generated by higher-level build systems and excels at incremental
build performance.

%prep
%autosetup -n ninja-%{version}

# Allow limiting jobs via the NINJAJOBS environment variable, matching MLFS guidance.
sed -i '/int Guess/a \
  int   j = 0;\
  char* jobs = getenv( "NINJAJOBS" );\
  if ( jobs != NULL ) j = atoi( jobs );\
  if ( j > 0 ) return j;\
' src/ninja.cc

%build
python3 configure.py --bootstrap --verbose

%install
rm -rf %{buildroot}
install -Dm755 ninja %{buildroot}/usr/bin/ninja
install -Dm644 misc/bash-completion \
  %{buildroot}/usr/share/bash-completion/completions/ninja
install -Dm644 misc/zsh-completion \
  %{buildroot}/usr/share/zsh/site-functions/_ninja

cd %{buildroot}
find . -type f -o -type l | sed 's|^\.||' > %{_builddir}/ninja-files.list

%files -f %{_builddir}/ninja-files.list
%defattr(-,root,root)

%changelog
* Tue Dec 23 2025 Juan Cuzmar <juan.cuzmar.s@gmail.com> - 1.13.2-1.m264
- Initial packaging aligned with MLFS 8.59 instructions.
